### Site Settings ###
title: Muhammad Anas Raza
description: >-
  ML | Learner
baseurl: "" # Set to the name of your GitHub repository, e.g., "/my-portfolio"
repository: anasrz-alt/anasrz-alt.github.io # Change to <your-username>/<your-username>.github.io
remote_theme: yousinix/portfolYOU
open_new_tab: false


### Plugins ###
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-target-blank


### Navbar Settings ###
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**


### Author Info ###
author:
  name: Muhammad Anas Raza
  image: # Add a URL for your profile picture here
  email: # Add your email here
  github: anasrz-alt
  linkedin: memanasraza
  stackoverflow: 13262692/muhammad-anas-raza
  # If you use Twitter, you can uncomment the line below and add your username
  # twitter: AnasRzaa


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: # Add your Disqus shortname here


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: # Add your Google Analytics tracking ID here


### Buy me a coffee ###
buymeacoffee:
  enabled: false
  username: # Add your username here
  color: "#007bff"
  message: "Thank you for visiting."
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"